server:
  port: 7070
  context-path: /api

security:
  oauth2:
    resource:
     id: 11010111
     jwt:
       key-uri: http://localhost:7071/oauth/token_key

spring:
  datasource:
    sql-script-encoding: utf-8
logging:
  level:
    cn.eastseven: debug
    org.springframework.security: debug

