spring.thymeleaf.cache: false
spring.thymeleaf.mode: HTML

spring.jpa.show-sql: true

logging.level.cn.eastseven: debug
logging.level.cn.eastseven.rbac.security.FilterSecurityInterceptorImpl: warn
logging.level.org.springframework.security: info

#server.error.whitelabel.enabled=false
security.enable-csrf: true
spring.datasource.sql-script-encoding: utf-8