gen.entity: |
  {
    "packageName": "cn.eastseven.hadoop.demo",
    "className": "UrlData",
    "tableName": "url_data",
    "properties": [
      {"name": "id", "type": "String"},
      {"name": "url", "type": "String"},
      {"name": "title", "type": "String"},
      {"name": "origin", "type": "String"},
      {"name": "seed", "type": "String"},
      {"name": "createTime", "type": "long"},
      {"name": "status", "type": "String"},
      {"name": "processorName", "type": "String"},
    ]
  }