version: '2'
services:
  hitchhiker:
    image: brookshi/hitchhiker:v0.8
    container_name: hitchhiker
    environment:
      - HITCHHIKER_DB_HOST=hitchhiker-mysql
      - HITCHHIKER_APP_HOST=http://localhost:8080/ # should change before deploying.
      # 在这里写入环境变量
    ports:
      - "8080:8080"
      - "11010:11010"
    links:
      - hitchhiker-mysql:hitchhiker-mysql
  hitchhiker-mysql:
    image: mysql:5.7
    container_name: hitchhiker-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hitchhiker888
      - MYSQL_DATABASE=hitchhiker-prod
    volumes:
      # - ./hitchhiker-mysql.cnf:/etc/mysql/conf.d/hitchhiker.cnf
      - ./target/hitchhiker-sqldata:/var/lib/mysql