version: '2'
services:
  app:
    image: cptactionhank/atlassian-jira:latest
    container_name: jira-data
    ports:
      - "18080:8080"
    volumes:
      - ./target/jira/data:/var/atlassian/jira
      - ./target/jira/logs:/opt/atlassian/jira/logs
    links:
      - mysql:mysql
  mysql:
    image: mariadb
    container_name: jira-db
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=jira
      - MYSQL_USER=jira
      - MYSQL_PASSWORD=123456
    volumes:
      - ./target/jira/mysql:/var/lib/mysql