version: '2'

services:
  mysql:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=hello
      - MYSQL_USER=d7
      - MYSQL_PASSWORD=654321
    volumes:
      - ./target/mariadb-db:/var/lib/mysql