# docker pull maxexcloo/nginx-php
version: '2'

services:
  app:
    image: maxexcloo/nginx-php
    ports:
      - 8765:80
    volumes:
      - ./target/nginx-php:/app
      - ./target/nginx-php-data:/data
    depends_on:
      - mysql
    links:
      - mysql:mysql  
  mysql:
    image: mariadb
    ports:
      - 8766:3306
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./target/mysql:/var/lib/mysql
