version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ROOT_PASSWORD=123456
      - MONGODB_USERNAME=test
      - MONGODB_PASSWORD=123456
      - MONGODB_DATABASE=test
    volumes:
      - ./target/mongodb-data:/bitnami