version: '2'

services:

  wordpress:
    image: wordpress
    depends_on:
      - mysql
    links:
      - mysql:mysql
    ports:
      - 8081:80
    environment:
      - WORDPRESS_DB_PASSWORD=example
    volumes:
      - ./target/wp:/var/www/html

  mysql:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./target/wpdb:/var/lib/mysql