logging:
  level:
    cn.eastseven.webcrawler: debug
    cn.eastseven.webcrawler.scheduler: info
#    us.codecraft.webmagic.downloader: error
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
  redis:
    host: 192.168.3.108
    port: 6379
    password: 123456
    pool:
      max-wait: 1234
      min-idle: 16
      max-idle: 32
      max-active: 16
  data:
    mongodb:
      host: 192.168.3.108
      port: 27017
      database: crawler
  application:
    name: web-crawler

app.proxy.pool:
  url: http://192.168.3.117:5000/get/
  urls: http://192.168.3.117:5000/get_all/

crawler.libs:
  phantomjs: libs/phantomjs/#/phantomjs
  selenium: libs/chromedriver/#/chromedriver