version: '2'

services:
  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - '16379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=123456
    volumes:
      - './../target/redis-master:/bitnami'

  redis-slave:
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=123456
      - REDIS_PASSWORD=654321
    volumes:
      - './../target/redis-slave:/bitnami'